theme: jekyll-theme-minimal
title: "Thomas Cross - Software Engineer & Founder"
description: "Software engineer, CTO, founder, and product builder in Omaha, Nebraska."
logo: /assets/img/logo.png
show_downloads: false
google_analytics: G-BP40Y02D81

plugins:
  - jekyll-sitemap
